"""M5.3 后续 — 项目笔记的 evidence block 幂等更新器。

设计契约（详见 docs/IMPLEMENTATION.md 的 project evidence 说明）：

1. **只更新受控区块**：在 ``30-Projects/<name>.md`` 中找
   ``<!-- MINDFORGE:EVIDENCE:START -->`` 与
   ``<!-- MINDFORGE:EVIDENCE:END -->`` 之间的内容；其余正文 / frontmatter
   一字不改。
2. **必须幂等**：多次运行同一命令产出相同的卡片清单时，文件内容除
   "Last updated:" 时间戳外应保持稳定；**绝不**重复追加块。
3. **缺块即追加**：如果文件不含 marker，在文末插入完整块（包含 marker）。
4. **profile 必须先存在**：若 ``30-Projects/<name>.md`` 不存在，本命令
   报错退出 2，**不**自动创建（防御："手滑打错项目名" 时静默生成空文件）。
5. **永不写敏感字段**：只写 ``id`` / ``title`` / ``rel_path`` / ``status`` /
   ``track`` / ``value_score`` / ``review_after``；**绝不**写 ai_summary
   / source_excerpt / 卡片正文 / prompt / completion / api_key / .env。
6. **永不修改 Knowledge Cards**：本模块对 ``20-Knowledge-Cards/`` 是
   严格只读。
7. **不调 LLM**；不调 .env；不调网络。
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from .cards import CardSummary

# 区块 marker — 与 README / 协议文档保持一致；改动需要 bump schema 版本
START_MARKER = "<!-- MINDFORGE:EVIDENCE:START -->"
END_MARKER = "<!-- MINDFORGE:EVIDENCE:END -->"


@dataclass(frozen=True)
class EvidenceUpdate:
    """update_evidence 的结果摘要（仅元数据，方便 telemetry / CLI 打印）。"""

    profile_path: Path
    rel_path: str
    project_name: str
    card_count: int
    block_existed_before: bool
    will_change: bool
    new_text: str  # 完整文件内容（含未改动的正文）；dry-run 用


class EvidenceError(ValueError):
    """profile 文件不存在 / 路径越界等明确错误。"""


# ---------------------------------------------------------------------------
# 公开 API
# ---------------------------------------------------------------------------


def update_evidence_block(
    profile_path: Path,
    project_name: str,
    cards: list[CardSummary],
    *,
    cards_dir_rel: str,
    now: datetime | None = None,
) -> EvidenceUpdate:
    """计算更新后的 profile 文件全文。

    ``cards`` 必须是调用方已经按"仅 human_approved（除非 --include-drafts）"
    过滤过的子集；本函数不再过滤，仅排序 + 渲染。

    返回 ``EvidenceUpdate``；不会落盘，是否落盘由 CLI 控制（dry-run 不写）。
    """
    if not profile_path.exists() or not profile_path.is_file():
        raise EvidenceError(
            f"项目 profile 不存在：{profile_path}；"
            f"请先手动创建 30-Projects/{project_name}.md（本命令故意不自动创建）。"
        )

    original = profile_path.read_text(encoding="utf-8")
    new_block = _render_block(cards, cards_dir_rel=cards_dir_rel, now=now)
    new_text, existed = _splice_block(original, new_block)
    rel = _safe_rel_to_vault(profile_path)
    return EvidenceUpdate(
        profile_path=profile_path,
        rel_path=rel,
        project_name=project_name,
        card_count=len(cards),
        block_existed_before=existed,
        will_change=(new_text != original),
        new_text=new_text,
    )


def write_evidence_update(update: EvidenceUpdate) -> None:
    """把 ``update.new_text`` 写回 profile 文件。

    幂等性保证由 ``update_evidence_block`` 输出决定（``new_text`` 中的卡片
    清单是排序去重后的）；本函数只是简单写盘。
    """
    update.profile_path.write_text(update.new_text, encoding="utf-8")


# ---------------------------------------------------------------------------
# 内部
# ---------------------------------------------------------------------------


def _render_block(
    cards: list[CardSummary],
    *,
    cards_dir_rel: str,
    now: datetime | None = None,
) -> str:
    """渲染 START/END marker 之间的内容（含 marker 行本身）。"""
    now = now or datetime.now(timezone.utc).astimezone()
    sorted_cards = sorted(
        cards,
        key=lambda c: ((c.id or c.path.stem).lower(), c.rel_path),
    )

    lines: list[str] = []
    lines.append(START_MARKER)
    lines.append("## MindForge Evidence")
    lines.append("")
    lines.append(f"Last updated: {now.isoformat(timespec='seconds')}")
    lines.append("")
    lines.append(
        "> Auto-generated by `mindforge project update-evidence`. "
        "MindForge only manages content **inside the markers**; "
        "everything else in this file is human-owned."
    )
    lines.append("")
    if not sorted_cards:
        lines.append("_(no approved cards yet for this project)_")
    else:
        for c in sorted_cards:
            link = _card_relative_link(c, cards_dir_rel)
            title = c.title or (c.id or c.path.stem)
            lines.append(f"- [{title}]({link})")
            lines.append(f"  - status: {c.status}")
            lines.append(f"  - learning_track: {c.track or '-'}")
            lines.append(
                f"  - value_score: {c.value_score if c.value_score is not None else '-'}"
            )
            lines.append(
                f"  - review_after: {c.review_after.date().isoformat() if c.review_after else '-'}"
            )
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def _splice_block(original: str, new_block: str) -> tuple[str, bool]:
    """把 ``new_block`` 嵌入 original；存在则替换、不存在则追加文末。

    返回 ``(new_text, block_existed_before)``。
    """
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        flags=re.DOTALL,
    )
    if pattern.search(original):
        new_text = pattern.sub(lambda _m: new_block, original, count=1)
        return new_text, True

    # 追加：保证与原文之间至少有一个空行；并保证文末有换行
    sep = "" if original.endswith("\n\n") else ("\n" if original.endswith("\n") else "\n\n")
    new_text = original + sep + new_block + "\n"
    return new_text, False


def _card_relative_link(card: CardSummary, cards_dir_rel: str) -> str:
    """把卡片渲染成相对 30-Projects/<name>.md 的链接。

    评估方式：30-Projects 与 cards_dir 通常都在 vault 根下平级，所以
    相对链接是 ``../<cards_dir>/<sub>/<file>.md``；这里直接用 vault
    相对路径反推：``rel_path`` 是 vault 根的 posix，所以前缀 ``../``。
    """
    rel = card.rel_path
    return f"../{rel}"


def _safe_rel_to_vault(p: Path) -> str:
    """尽力给一个 posix 字符串；失败回退到文件名。"""
    return p.name if not p.parent else f"{p.parent.name}/{p.name}"


__all__ = [
    "END_MARKER",
    "START_MARKER",
    "EvidenceError",
    "EvidenceUpdate",
    "update_evidence_block",
    "write_evidence_update",
]
