"""M5.3 后续 — 多 project 联合上下文渲染（**安全拼装，非 RAG**）。

为什么"多 project context"仍然不是 RAG：

- 数据源仍然只是 ``20-Knowledge-Cards/`` 与 ``30-Projects/<name>.md``
  frontmatter；**不**做 embedding、**不**算相似度、**不**调 LLM；
- 所谓"联合"只是把多个项目共享的卡片做 **集合并 + path-level 去重**，
  按"项目 → 卡片"关系结构化分组输出；
- suggested prompt 是固定模板拼装，明确告诉下游 agent："你拿到的是
  多项目上下文包，原则可能并存且**未自动裁决**"。

输出结构（与单 project 渲染器互补）：

1. Project Overview            — 项目计数 + 名称列表 + target
2. Source Notice               — 每个项目的 profile_found / 路径
3. Project Profiles            — 每个项目的 description / preferred_workflow
4. Cross-project Learning Tracks — 跨项目卡片的 track 累计
5. Cross-project Principles    — 项目级 + 卡片级；按 (project / card) 来源标注
6. Cross-project Known Risks   — 同上
7. Project-specific Cards      — 按项目分组；卡片去重，归入第一个匹配项目
8. Shared Action Items         — 跨项目的 action_items（按卡片合并）
9. Review Due                  — 跨项目复习清单
10. Suggested Prompt for <target> — 注明这是 multi-project context pack
11. Excluded Content           — 与单项目一致的安全清单
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

from .cards import CardSummary, extract_section
from .project_context import (
    EXCLUDED_CONTENT,
    ProjectContextOptions,
    _d,
    _due_now,
    _overdue_days,
    _safe_body,
    _select,
    _TARGET_STYLE,
)
from .project_profile import ProjectProfile


def render_multi_project_context_markdown(
    project_names: list[str],
    cards_by_project: dict[str, list[CardSummary]],
    profiles: dict[str, ProjectProfile],
    *,
    options: ProjectContextOptions,
) -> str:
    """多 project markdown 渲染（thin orchestrator）。

    架构边界（Residual Architecture Debt Closure Pack）：

    - 这里只负责 **section 顺序编排** 与公共上下文（``selected_by_project``、
      ``all_selected``、``now_iso``）准备；
    - 11 个具名段落各自下沉到 ``_section_*`` 私有 helper，每个 helper 单一
      职责、易于阅读与回归测试；
    - 不变量：所有 section 的 header / 内容 / 顺序 / 可选开关与原实现完全
      一致；外部行为零变化；
    - ``cards_by_project`` 的 status / drafts 过滤仍由调用方负责。
    """
    assert len(project_names) >= 2, "multi-project 渲染至少需要 2 个项目"

    selected_by_project = _select_and_dedup(project_names, cards_by_project, options)
    all_selected = [c for cs in selected_by_project.values() for c in cs]
    now_iso = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")

    lines: list[str] = []
    lines.extend(_section_overview(project_names, options, now_iso))
    lines.extend(_section_source_notice(project_names, profiles, selected_by_project))
    lines.extend(_section_project_profiles(project_names, profiles))
    lines.extend(_section_cross_tracks(all_selected))
    lines.extend(_section_cross_principles(project_names, profiles, selected_by_project))
    lines.extend(_section_cross_risks(project_names, profiles, selected_by_project))
    lines.extend(_section_project_specific_cards(project_names, selected_by_project))
    if options.include_actions:
        lines.extend(_section_shared_action_items(all_selected))
    if options.include_review_due:
        lines.extend(_section_review_due(all_selected))
    if options.include_next_step_prompt:
        lines.extend(_section_suggested_prompt(project_names, profiles, options))
    lines.extend(_section_excluded_content())

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Section helpers — 每个返回 list[str]（不含尾部换行；由 orchestrator 用 \n join）。
# 拆分理由：原 178 行 god-renderer 同时承担 11 个独立段落 + 数据准备 + 排序，
# 违反单一职责。helper 化后：
#   * 每个段落独立可读、可单测；
#   * orchestrator 退化为段落顺序声明，便于审计 section 顺序与可选段。
# 不变量（与原实现严格一致）：header 字面、可选段开关、顺序、空态文案。
# ---------------------------------------------------------------------------


def _section_overview(
    project_names: list[str],
    options: ProjectContextOptions,
    now_iso: str,
) -> list[str]:
    """1. Project Overview — 标题 + 生成时间 + 项目列表 + drafts 提示。"""
    lines = [
        f"# Multi-Project Context · {' · '.join(project_names)}\n",
        f"> Generated by mindforge project context at {now_iso}",
        f"> projects: {project_names} (count={len(project_names)})",
        f"> target: {options.target}",
    ]
    if options.include_drafts:
        lines.append("> 包含 ai_draft 卡片（--include-drafts）")
    else:
        lines.append("> 仅含 status=human_approved 的卡片摘要")
    lines.append("> 多项目模式：来源透明、原则不自动裁决（详见 Cross-project Principles）\n")
    return lines


def _section_source_notice(
    project_names: list[str],
    profiles: dict[str, ProjectProfile],
    selected_by_project: dict[str, list[CardSummary]],
) -> list[str]:
    """2. Source Notice — 每个项目的 profile 来源 + 去重后总卡数。"""
    lines = ["## Source Notice"]
    for name in project_names:
        prof = profiles[name]
        if prof.found:
            lines.append(f"- {name}: project_profile_found=true ({prof.rel_path})")
        else:
            lines.append(
                f"- {name}: project_profile_found=false (using Knowledge Cards only)"
            )
    total_unique = sum(len(cs) for cs in selected_by_project.values())
    lines.append(f"- total_unique_cards (after dedup across projects): {total_unique}")
    lines.append("")
    return lines


def _section_project_profiles(
    project_names: list[str],
    profiles: dict[str, ProjectProfile],
) -> list[str]:
    """3. Project Profiles — 每项目的 description + preferred_workflow。"""
    lines = ["## Project Profiles"]
    for name in project_names:
        prof = profiles[name]
        lines.append(f"### {name}")
        if not prof.found:
            lines.append("- (no profile configured)")
            lines.append("")
            continue
        lines.append(f"- description: {prof.description or 'No description configured.'}")
        lines.append("- preferred_workflow:")
        if prof.preferred_workflow:
            for w in prof.preferred_workflow:
                lines.append(f"  - {w}")
        else:
            lines.append("  - No preferred_workflow configured.")
        lines.append("")
    return lines


def _section_cross_tracks(all_selected: list[CardSummary]) -> list[str]:
    """4. Cross-project Learning Tracks — 累计 track 计数（按数量降序）。"""
    lines = ["## Cross-project Learning Tracks"]
    track_counts: dict[str, int] = {}
    for c in all_selected:
        if c.track:
            track_counts[c.track] = track_counts.get(c.track, 0) + 1
    if not track_counts:
        lines.append("- (no learning_track found across selected cards)")
    else:
        for t, n in sorted(track_counts.items(), key=lambda kv: (-kv[1], kv[0])):
            lines.append(f"- {t} ({n} card{'s' if n != 1 else ''})")
    lines.append("")
    return lines


def _section_cross_principles(
    project_names: list[str],
    profiles: dict[str, ProjectProfile],
    selected_by_project: dict[str, list[CardSummary]],
) -> list[str]:
    """5. Cross-project Principles — 项目级 + 卡片级并列展示，不自动裁决。"""
    lines = ["## Cross-project Principles"]
    any_principles = False
    for name in project_names:
        for p in profiles[name].principles:
            lines.append(f"- from project [{name}]: {p}")
            any_principles = True
    for name in project_names:
        for c in selected_by_project.get(name, []):
            cid = c.id or c.path.stem
            for p in c.principles:
                lines.append(f"- from card [{cid}] (project {name}): {p}")
                any_principles = True
    if not any_principles:
        lines.append("- No principles found at project- or card-level.")
    lines.append("")
    return lines


def _section_cross_risks(
    project_names: list[str],
    profiles: dict[str, ProjectProfile],
    selected_by_project: dict[str, list[CardSummary]],
) -> list[str]:
    """6. Cross-project Known Risks — 项目级 + 卡片级风险并列。"""
    lines = ["## Cross-project Known Risks"]
    any_risks = False
    for name in project_names:
        for r in profiles[name].known_risks:
            lines.append(f"- from project [{name}]: {r}")
            any_risks = True
    for name in project_names:
        for c in selected_by_project.get(name, []):
            cid = c.id or c.path.stem
            for r in c.known_risks:
                lines.append(f"- from card [{cid}] (project {name}): {r}")
                any_risks = True
    if not any_risks:
        lines.append("- No known_risks found at project- or card-level.")
    lines.append("")
    return lines


def _section_project_specific_cards(
    project_names: list[str],
    selected_by_project: dict[str, list[CardSummary]],
) -> list[str]:
    """7. Project-specific Cards — 去重后按项目分组；空项目仍显式展示。"""
    lines = ["## Project-specific Cards"]
    for name in project_names:
        cs = selected_by_project.get(name, [])
        lines.append(f"### {name} ({len(cs)} card{'s' if len(cs) != 1 else ''})")
        if not cs:
            lines.append("- (no cards matched)")
            lines.append("")
            continue
        for c in cs:
            cid = c.id or c.path.stem
            lines.append(
                f"- [{cid}] {c.title or '(untitled)'} · "
                f"track: {c.track or '-'} · status: {c.status} · "
                f"value_score: {c.value_score if c.value_score is not None else '-'}"
            )
            lines.append(f"  - path: {c.rel_path}")
        lines.append("")
    return lines


def _section_shared_action_items(all_selected: list[CardSummary]) -> list[str]:
    """8. Shared Action Items — 跨项目按卡片合并的 action 列表。"""
    lines = ["## Shared Action Items"]
    aggregated: list[str] = []
    for c in all_selected:
        body = _safe_body(c.path)
        if not body:
            continue
        seg = extract_section(body, "Action Items")
        if seg:
            cid = c.id or c.path.stem
            aggregated.append(f"- from [{cid}]:\n{_indent(seg)}")
    if not aggregated:
        lines.append("- (no action items)")
    else:
        lines.extend(aggregated)
    lines.append("")
    return lines


def _section_review_due(all_selected: list[CardSummary]) -> list[str]:
    """9. Review Due — 跨项目复习提醒。"""
    lines = ["## Review Due"]
    due = _due_now(all_selected)
    if not due:
        lines.append("- (none due)")
    else:
        for c in due:
            cid = c.id or c.path.stem
            overdue = _overdue_days(c.review_after)
            tail = f" (overdue {overdue} days)" if overdue > 0 else " (due now)"
            lines.append(f"- [{cid}]{tail}")
    lines.append("")
    return lines


def _section_suggested_prompt(
    project_names: list[str],
    profiles: dict[str, ProjectProfile],
    options: ProjectContextOptions,
) -> list[str]:
    """10. Suggested Prompt — 固定模板拼装 next-step prompt。"""
    return [
        f"## Suggested Prompt for {options.target}\n",
        "```text",
        _render_multi_suggested_prompt(project_names, options.target, profiles),
        "```",
        "",
    ]


def _section_excluded_content() -> list[str]:
    """11. Excluded Content — 安全清单（共享自单 project 渲染器）。"""
    lines = ["## Excluded Content (safety guarantee)"]
    for item in EXCLUDED_CONTENT:
        lines.append(f"- {item}")
    return lines


def render_multi_project_context_json(
    project_names: list[str],
    cards_by_project: dict[str, list[CardSummary]],
    profiles: dict[str, ProjectProfile],
    *,
    options: ProjectContextOptions,
) -> str:
    """多 project JSON v2 渲染（schema 与单项目 v2 兼容，结构按多项目展开）。"""
    assert len(project_names) >= 2

    selected_by_project = _select_and_dedup(project_names, cards_by_project, options)
    all_selected = [c for cs in selected_by_project.values() for c in cs]
    now_iso = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")

    track_counts: dict[str, int] = {}
    for c in all_selected:
        if c.track:
            track_counts[c.track] = track_counts.get(c.track, 0) + 1

    payload = {
        "version": 2,
        "mode": "multi_project",
        "projects": project_names,
        "project_count": len(project_names),
        "generated_at": now_iso,
        "target": options.target,
        "include_drafts": options.include_drafts,
        "include_prompts": options.include_prompts,
        "include_actions": options.include_actions,
        "include_review_due": options.include_review_due,
        "include_next_step_prompt": options.include_next_step_prompt,
        "total_unique_cards": sum(len(cs) for cs in selected_by_project.values()),
        "project_profiles": [
            {
                "project": name,
                "found": profiles[name].found,
                "rel_path": profiles[name].rel_path,
                "description": profiles[name].description,
                "preferred_workflow": list(profiles[name].preferred_workflow),
                "principles": list(profiles[name].principles),
                "known_risks": list(profiles[name].known_risks),
            }
            for name in project_names
        ],
        "cross_project_learning_tracks": [
            {"track": t, "count": n}
            for t, n in sorted(track_counts.items(), key=lambda kv: (-kv[1], kv[0]))
        ],
        "cross_project_principles": _collect_cross_principles(
            project_names, profiles, selected_by_project, "principles"
        ),
        "cross_project_known_risks": _collect_cross_principles(
            project_names, profiles, selected_by_project, "known_risks"
        ),
        "project_specific_cards": [
            {
                "project": name,
                "count": len(selected_by_project.get(name, [])),
                "items": [_card_json_min(c) for c in selected_by_project.get(name, [])],
            }
            for name in project_names
        ],
        "suggested_prompt": _render_multi_suggested_prompt(
            project_names, options.target, profiles
        ),
        "excluded_content": list(EXCLUDED_CONTENT),
    }
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False)


# ---------------------------------------------------------------------------
# 内部
# ---------------------------------------------------------------------------


def _select_and_dedup(
    project_names: list[str],
    cards_by_project: dict[str, list[CardSummary]],
    options: ProjectContextOptions,
) -> dict[str, list[CardSummary]]:
    """按用户给的项目顺序对卡片做 path-level 去重；先到先得。

    幂等性：相同输入产出顺序稳定（依赖 ``_select`` 的稳定排序）。
    """
    seen: set[str] = set()
    out: dict[str, list[CardSummary]] = {}
    for name in project_names:
        cards = cards_by_project.get(name, [])
        selected = _select(cards, options)
        kept: list[CardSummary] = []
        for c in selected:
            key = str(c.path)
            if key in seen:
                continue
            seen.add(key)
            kept.append(c)
        out[name] = kept
    return out


def _collect_cross_principles(
    project_names: list[str],
    profiles: dict[str, ProjectProfile],
    selected_by_project: dict[str, list[CardSummary]],
    field_name: str,
) -> list[dict]:
    """聚合跨项目的 principles / known_risks，每条标注 source（project / card）。"""
    out: list[dict] = []
    for name in project_names:
        prof = profiles[name]
        items = getattr(prof, field_name, ())
        for it in items:
            out.append({"source_kind": "project", "source_id": name, "item": it})
    for name in project_names:
        for c in selected_by_project.get(name, []):
            cid = c.id or c.path.stem
            items = getattr(c, field_name, ())
            for it in items:
                out.append(
                    {
                        "source_kind": "card",
                        "source_id": cid,
                        "project": name,
                        "item": it,
                    }
                )
    return out


def _render_multi_suggested_prompt(
    project_names: list[str],
    target: str,
    profiles: dict[str, ProjectProfile],
) -> str:
    """多项目 suggested prompt（仍是固定模板拼装；**绝不**调 LLM）。

    与单项目模板的区别：明确声明这是 "multi-project context pack"，原则
    可能并存且**未自动裁决**，要求下游 agent 在用之前先确认是否冲突。
    """
    target_norm = target if target in _TARGET_STYLE else "generic"
    parts: list[str] = []
    parts.append(
        "你拿到的是 mindforge 生成的 **multi-project context pack**。\n"
        f"涉及项目：{', '.join(project_names)}（共 {len(project_names)} 个）；"
        f"target={target_norm}。\n"
        "\n"
        "工作前请按以下规则处理：\n"
        "\n"
        "1. 上下文里同时包含多个项目的 principles 与 known_risks，"
        "**MindForge 不自动裁决冲突**；如发现两个项目的原则相互矛盾，请先停下来"
        "向我确认本次任务以哪个项目为主；\n"
        "2. 不要捏造没有出现在上下文中的事实；\n"
        "3. 你的产出要明确区分"
        "「来自上下文的事实」与「你的推断」；\n"
        "4. 不要试图读取或修改 .env / runs / state.json；\n"
        "5. 涉及代码改动时，先列文件路径、再给 diff 或最小补丁；\n"
        "6. 如果你的改动只关心其中某一个项目，请在产出开头声明 "
        '"focused_project: <name>"，避免把跨项目原则当成单项目结论。'
    )
    parts.append("")
    parts.append(_TARGET_STYLE[target_norm])

    # 仅展示 found=true 的项目级 principles / preferred_workflow
    for name in project_names:
        prof = profiles[name]
        if not prof.found:
            continue
        if prof.principles:
            parts.append("")
            parts.append(f"项目 [{name}] 的 principles：")
            parts.extend(f"- {p}" for p in prof.principles)
        if prof.preferred_workflow:
            parts.append("")
            parts.append(f"项目 [{name}] 的 preferred_workflow：")
            parts.extend(f"- {w}" for w in prof.preferred_workflow)

    return "\n".join(parts)


def _card_json_min(c: CardSummary) -> dict:
    """多项目 JSON 输出仅展示卡片的安全元数据（不含正文段落）。"""
    return {
        "id": c.id,
        "title": c.title,
        "path": c.rel_path,
        "status": c.status,
        "track": c.track,
        "projects": list(c.projects),
        "tags": list(c.tags),
        "source_type": c.source_type,
        "source_url": c.source_url,
        "value_score": c.value_score,
        "reviewed_at": c.reviewed_at.isoformat() if c.reviewed_at else None,
        "review_after": c.review_after.isoformat() if c.review_after else None,
        "principles": list(c.principles),
        "known_risks": list(c.known_risks),
    }


def _indent(s: str, prefix: str = "  ") -> str:
    return "\n".join(prefix + line for line in s.splitlines())


# 让 ruff 别误删（这两个仅在 markdown 段被 _d 等用到，多项目里已直接 import 它们）
_ = _d


__all__ = [
    "render_multi_project_context_json",
    "render_multi_project_context_markdown",
]
