"""M5.3 — project context pack 渲染器（**只读**）。

固定结构见 docs/M5_3_PROJECT_CONTEXT_PROTOCOL.md。

约束（v0.1 → v0.2.2 一脉相承）：

- 不调 LLM；不读 .env；不读 runs/state；不读 raw source；
- 输出**不**含 ``AI Inference (low confidence)`` 段；
- 输出**不**含 ``Human Note`` 段；
- 输出**不**含 secret / api_key / source raw_text；
- 默认仅 ``status=human_approved``；``--include-drafts`` 才带 ai_draft；
- 项目 profile **只读 frontmatter**，永不读其正文。
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from .cards import CardSummary, extract_section, read_card_body
from .project_profile import VALID_TARGETS, ProjectProfile

# 排除内容清单（markdown 与 json 输出共用，**禁止**修改成"按情况隐藏"）
EXCLUDED_CONTENT: tuple[str, ...] = (
    "raw source (00-Inbox/**)",
    "AI Inference (low confidence)",
    "Human Note section",
    "secrets / api_key / Authorization headers",
    "runs jsonl / state.json",
    "LLM prompt full text / completion text",
)


@dataclass(frozen=True)
class ProjectContextOptions:
    include_prompts: bool = True
    include_drafts: bool = False
    include_actions: bool = True
    include_review_due: bool = True
    include_next_step_prompt: bool = True
    limit: int = 20
    target: str = "generic"  # M5.3：claude-code | copilot | codex | generic


def resolve_target(cli_target: str | None, profile: ProjectProfile) -> str:
    """按 §2.2 顺序解析 target：cli > profile.default_target > generic。"""
    if cli_target:
        if cli_target not in VALID_TARGETS:
            raise ValueError(
                f"--target 必须是 {sorted(VALID_TARGETS)} 之一，收到 {cli_target!r}"
            )
        return cli_target
    if profile.default_target:
        return profile.default_target
    return "generic"


# ---------------------------------------------------------------------------
# Markdown 渲染
# ---------------------------------------------------------------------------


def render_project_context_markdown(
    project_name: str,
    cards: list[CardSummary],
    *,
    options: ProjectContextOptions,
    profile: ProjectProfile | None = None,
) -> str:
    """渲染固定结构的 markdown context pack（v0.2.2 schema）。"""
    profile = profile or ProjectProfile(
        project_name=project_name, found=False, rel_path=None
    )
    selected = _select(cards, options)
    now_iso = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")

    lines: list[str] = []
    # ---- Header ----
    lines.append(f"# Project Context · {project_name}\n")
    lines.append(f"> Generated by mindforge project context at {now_iso}")
    lines.append(f"> target: {options.target}")
    if options.include_drafts:
        lines.append("> 包含 ai_draft 卡片（--include-drafts）")
    else:
        lines.append("> 仅含 status=human_approved 的卡片摘要")
    lines.append(
        "> 字段范围：见 docs/M5_3_PROJECT_CONTEXT_PROTOCOL.md（v0.2.2）\n"
    )

    # ---- Source Notice ----
    lines.append("## Source Notice")
    lines.append(f"- project_profile_found: {str(profile.found).lower()}")
    if profile.found:
        lines.append(f"- project_profile_path: {profile.rel_path}")
    elif profile.rel_path:
        lines.append(f"- project_profile_path: {profile.rel_path} (parse failed)")
    else:
        lines.append("- project_profile_path: (not found)")
    lines.append(f"- card_count: {len(selected)}")
    if not profile.found and profile.rel_path is None:
        lines.append(
            f"- note: No project profile found at "
            f"`30-Projects/{project_name}.md`; using Knowledge Cards only."
        )
    lines.append("")

    # ---- Project Profile ----
    lines.append("## Project Profile")
    lines.append(
        f"- description: {profile.description or 'No description configured.'}"
    )
    lines.append("- preferred_workflow:")
    if profile.preferred_workflow:
        for w in profile.preferred_workflow:
            lines.append(f"  - {w}")
    else:
        lines.append("  - No preferred_workflow configured.")
    lines.append("")

    # ---- Project-Level Principles ----
    lines.append("## Project-Level Principles")
    if profile.principles:
        for p in profile.principles:
            lines.append(f"- {p}")
    else:
        lines.append("- No project-level principles configured.")
    lines.append("")

    # ---- Card-Level Principles (supplementary) ----
    lines.append("## Card-Level Principles (supplementary)")
    card_principles = _collect_card_field(selected, "principles")
    if card_principles:
        for cid, items in card_principles:
            for it in items:
                lines.append(f"- from [{cid}]: {it}")
    else:
        lines.append("- No card-level principles found.")
    lines.append("")

    # ---- Project-Level Known Risks ----
    lines.append("## Project-Level Known Risks")
    if profile.known_risks:
        for r in profile.known_risks:
            lines.append(f"- {r}")
    else:
        lines.append("- No project-level known_risks configured.")
    lines.append("")

    # ---- Card-Level Known Risks (supplementary) ----
    lines.append("## Card-Level Known Risks (supplementary)")
    card_risks = _collect_card_field(selected, "known_risks")
    if card_risks:
        for cid, items in card_risks:
            for it in items:
                lines.append(f"- from [{cid}]: {it}")
    else:
        lines.append("- No card-level known_risks found.")
    lines.append("")

    # ---- Related Learning Tracks ----
    track_counts: dict[str, int] = {}
    for c in selected:
        if c.track:
            track_counts[c.track] = track_counts.get(c.track, 0) + 1
    lines.append("## Related Learning Tracks")
    if not track_counts:
        lines.append("- (none)")
    else:
        for t, n in sorted(track_counts.items(), key=lambda kv: (-kv[1], kv[0])):
            lines.append(f"- {t} ({n} card{'s' if n != 1 else ''})")
    lines.append("")

    # ---- Knowledge Cards ----
    lines.append("## Knowledge Cards (sorted by review_after asc, then value_score desc)")
    if not selected:
        lines.append("\n_(no cards matched)_\n")
    for c in selected:
        lines.append("")
        lines.append(f"### [{c.id or c.path.stem}] {c.title or '(untitled)'}")
        lines.append(
            f"- track: {c.track or '-'} · status: {c.status} · "
            f"value_score: {c.value_score if c.value_score is not None else '-'}"
        )
        if c.source_url:
            lines.append(f"- source: {c.source_url} ({c.source_type or '-'})")
        else:
            lines.append(f"- source: ({c.source_type or '-'})")
        if c.reviewed_at or c.review_after:
            lines.append(
                f"- reviewed_at: {_d(c.reviewed_at)} · review_after: {_d(c.review_after)}"
            )
        lines.append(f"- path: {c.rel_path}")

        body = _safe_body(c.path)
        excerpt = extract_section(body, "Source Excerpt") if body else None
        ai_summary = extract_section(body, "AI Summary") if body else None
        prompts = (
            extract_section(body, "Reusable Prompts / Principles") if body else None
        )

        if excerpt:
            lines.append("\n#### Source Excerpt")
            lines.append(excerpt)
        if ai_summary:
            lines.append("\n#### AI Summary")
            lines.append(ai_summary)
        if options.include_prompts and prompts:
            lines.append("\n#### Reusable Prompts / Principles")
            lines.append(prompts)

    # ---- Action Items ----
    if options.include_actions:
        lines.append("\n## Action Items")
        aggregated: list[str] = []
        for c in selected:
            body = _safe_body(c.path)
            if not body:
                continue
            seg = extract_section(body, "Action Items")
            if seg:
                aggregated.append(f"- from [{c.id or c.path.stem}]:\n{_indent(seg)}")
        if not aggregated:
            lines.append("_(no action items)_")
        else:
            lines.extend(aggregated)

    # ---- Review Due ----
    if options.include_review_due:
        lines.append("\n## Review Due")
        due = _due_now(selected)
        if not due:
            lines.append("_(none due)_")
        else:
            for c in due:
                overdue = _overdue_days(c.review_after)
                lines.append(
                    f"- [{c.id or c.path.stem}]"
                    + (f" (overdue {overdue} days)" if overdue > 0 else " (due now)")
                )

    # ---- Suggested Prompt for <target> ----
    if options.include_next_step_prompt:
        lines.append(f"\n## Suggested Prompt for {options.target}\n")
        lines.append("```text")
        lines.append(_render_suggested_prompt(project_name, options.target, profile))
        lines.append("```")

    # ---- Excluded Content ----
    lines.append("\n## Excluded Content (safety guarantee)")
    for item in EXCLUDED_CONTENT:
        lines.append(f"- {item}")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# JSON 渲染
# ---------------------------------------------------------------------------


def render_project_context_json(
    project_name: str,
    cards: list[CardSummary],
    *,
    options: ProjectContextOptions,
    profile: ProjectProfile | None = None,
) -> str:
    profile = profile or ProjectProfile(
        project_name=project_name, found=False, rel_path=None
    )
    selected = _select(cards, options)
    now_iso = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
    suggested_prompt = _render_suggested_prompt(
        project_name, options.target, profile
    )

    payload = {
        "version": 2,
        "project": project_name,
        "generated_at": now_iso,
        "target": options.target,
        "include_drafts": options.include_drafts,
        "include_prompts": options.include_prompts,
        "include_actions": options.include_actions,
        "include_review_due": options.include_review_due,
        "include_next_step_prompt": options.include_next_step_prompt,
        "count": len(selected),

        "project_profile_found": profile.found,
        "project_profile_path": profile.rel_path,
        "project_description": profile.description,
        "preferred_workflow": list(profile.preferred_workflow),
        "project_level_principles": list(profile.principles),
        "card_level_principles": [
            {"card_id": cid, "items": list(items)}
            for cid, items in _collect_card_field(selected, "principles")
        ],
        "project_level_known_risks": list(profile.known_risks),
        "card_level_known_risks": [
            {"card_id": cid, "items": list(items)}
            for cid, items in _collect_card_field(selected, "known_risks")
        ],

        "items": [_card_json(c, include_prompts=options.include_prompts) for c in selected],
        "suggested_prompt": suggested_prompt,
        "excluded_content": list(EXCLUDED_CONTENT),
    }
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False)


# ---------------------------------------------------------------------------
# Suggested Prompt 模板（**固定文本，绝不调 LLM**）
# ---------------------------------------------------------------------------

_TARGET_STYLE: dict[str, str] = {
    "claude-code": (
        "工作风格指令（claude-code）：\n"
        "- 先看真实事件链路（日志 / checkpoint / runtime_observer / state\n"
        "  / 真实 events）再决定改不改代码；\n"
        "- 不要只根据 UI 表象打补丁；\n"
        "- 产出 3 步建议：next-action / verification / risk。"
    ),
    "copilot": (
        "工作风格指令（copilot）：\n"
        "- 先 plan（列出受影响文件 + 测试范围），再小步实现；\n"
        "- 每个改动后必须给出验证命令（pytest / ruff / smoke）；\n"
        "- 遇到不确定的设计点，先给 2–3 个选项与 trade-off 让我选，再实施。"
    ),
    "codex": (
        "工作风格指令（codex）：\n"
        "- 仅提交「高质量补丁 + 测试」；\n"
        "- 不引入未列出的依赖；不做超出请求范围的重构；\n"
        "- 如发现 root cause 与请求不一致，先停下来汇报再继续。"
    ),
    "generic": (
        "工作风格指令（generic）：\n"
        "- 通用安全开发版本：plan → patch → test → report；\n"
        "- 任何破坏性操作（删文件 / 改 schema / 改 lockfile）必须先确认。"
    ),
}


def _render_suggested_prompt(
    project_name: str, target: str, profile: ProjectProfile
) -> str:
    """按 §4 拼装 suggested prompt。**纯字符串拼接**，无 LLM。"""
    target_norm = target if target in _TARGET_STYLE else "generic"
    parts: list[str] = []
    parts.append(
        f"你是我在 {project_name} 项目上的协作助手（target={target_norm}）。\n"
        "mindforge 已经把已审核的项目上下文打包给你（project profile +\n"
        "卡片摘要 + 行动项 + 风险 + 复习清单）。请严格按以下规则工作：\n"
        "\n"
        "1. 不要捏造没有出现在上下文中的事实；\n"
        "2. 你的产出要明确区分「来自上下文的事实」与「你的推断」；\n"
        "3. 不要试图读取或修改 .env / runs / state.json；\n"
        "4. 涉及代码改动时，先列文件路径、再给 diff 或最小补丁；\n"
        "5. 如果项目 profile 列出了 principles / known_risks，请优先遵守。"
    )
    parts.append("")
    parts.append(_TARGET_STYLE[target_norm])

    if profile.principles:
        parts.append("")
        parts.append("项目级 principles：")
        parts.extend(f"- {p}" for p in profile.principles)
    if profile.preferred_workflow:
        parts.append("")
        parts.append("项目级 preferred_workflow：")
        parts.extend(f"- {w}" for w in profile.preferred_workflow)

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# 内部
# ---------------------------------------------------------------------------


def _select(cards: list[CardSummary], options: ProjectContextOptions) -> list[CardSummary]:
    sorted_cards = sorted(cards, key=_sort_key)
    return sorted_cards[: options.limit]


def _sort_key(c: CardSummary) -> tuple[int, datetime, int, str]:
    has_after = 0 if c.review_after is not None else 1
    after = c.review_after or datetime.max.replace(tzinfo=timezone.utc)
    score = -(c.value_score or 0)
    return (has_after, after, score, c.id or c.path.name)


def _safe_body(path: Path) -> str | None:
    try:
        return read_card_body(path)
    except Exception:
        return None


def _d(dt: datetime | None) -> str:
    if dt is None:
        return "-"
    return dt.date().isoformat()


def _overdue_days(review_after: datetime | None) -> int:
    if review_after is None:
        return 0
    now = datetime.now(timezone.utc).astimezone()
    delta = (now - review_after).total_seconds() / 86400.0
    return max(0, int(delta))


def _due_now(cards: list[CardSummary]) -> list[CardSummary]:
    now = datetime.now(timezone.utc).astimezone()
    return [c for c in cards if c.review_after is not None and c.review_after <= now]


def _indent(s: str, prefix: str = "  ") -> str:
    return "\n".join(prefix + line for line in s.splitlines())


def _collect_card_field(
    cards: list[CardSummary], field_name: str
) -> list[tuple[str, tuple[str, ...]]]:
    """聚合 cards 中某结构化字段（principles / known_risks）。

    保留来源：返回 [(card_id, items), ...]，上层渲染时打 ``from [card-id]``
    标签，让 context 消费方明确"补充级"vs"项目级"。
    """
    out: list[tuple[str, tuple[str, ...]]] = []
    for c in cards:
        items = getattr(c, field_name, ())
        if items:
            cid = c.id or c.path.stem
            out.append((cid, tuple(items)))
    return out


def _card_json(c: CardSummary, *, include_prompts: bool) -> dict:
    body = _safe_body(c.path)
    summary_seg = extract_section(body, "AI Summary") if body else None
    excerpt_seg = extract_section(body, "Source Excerpt") if body else None
    prompts_seg = (
        extract_section(body, "Reusable Prompts / Principles") if body else None
    )
    return {
        "id": c.id,
        "title": c.title,
        "path": c.rel_path,
        "status": c.status,
        "track": c.track,
        "projects": list(c.projects),
        "tags": list(c.tags),
        "source_type": c.source_type,
        "source_url": c.source_url,
        "value_score": c.value_score,
        "reviewed_at": c.reviewed_at.isoformat() if c.reviewed_at else None,
        "review_after": c.review_after.isoformat() if c.review_after else None,
        "source_excerpt": excerpt_seg,
        "ai_summary": summary_seg,
        "reusable_prompts": prompts_seg if include_prompts else None,
        "principles": list(c.principles),
        "known_risks": list(c.known_risks),
    }


__all__ = [
    "ProjectContextOptions",
    "EXCLUDED_CONTENT",
    "render_project_context_markdown",
    "render_project_context_json",
    "resolve_target",
]
