"""M4 — project context pack 渲染器（**只读**）。

固定结构见 docs/M4_RECALL_REVIEW_PROTOCOL.md §6.2。

约束：
- 不调 LLM；仅做字段拼接与正文段落抽取；
- 输出**不**含 ``AI Inference (low confidence)`` 段；
- 输出**不**含 ``Human Note`` 段；
- 输出**不**含 secret / api_key / source raw_text；
- 默认包含 ``Reusable Prompts / Principles`` 段，可关。
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from .cards import CardSummary, extract_section, read_card_body


@dataclass(frozen=True)
class ProjectContextOptions:
    include_prompts: bool = True
    include_drafts: bool = False
    limit: int = 20


def render_project_context_markdown(
    project_name: str,
    cards: list[CardSummary],
    *,
    options: ProjectContextOptions,
) -> str:
    """渲染固定结构的 markdown context pack。"""
    selected = _select(cards, options)
    now_iso = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")

    lines: list[str] = []
    lines.append(f"# Project Context · {project_name}\n")
    lines.append(f"> Generated by mindforge project context at {now_iso}")
    if options.include_drafts:
        lines.append("> 包含 ai_draft 卡片（--include-drafts）")
    else:
        lines.append("> 仅含 status=human_approved 的卡片摘要")
    lines.append("> 字段范围：见 docs/M4_RECALL_REVIEW_PROTOCOL.md §5.3\n")

    # Related learning tracks
    track_counts: dict[str, int] = {}
    for c in selected:
        if c.track:
            track_counts[c.track] = track_counts.get(c.track, 0) + 1
    lines.append("## Related Learning Tracks")
    if not track_counts:
        lines.append("- (none)")
    else:
        for t, n in sorted(track_counts.items(), key=lambda kv: (-kv[1], kv[0])):
            lines.append(f"- {t} ({n} card{'s' if n != 1 else ''})")
    lines.append("")

    # Knowledge cards
    lines.append("## Knowledge Cards (sorted by review_after asc, then value_score desc)")
    if not selected:
        lines.append("\n_(no cards matched)_\n")
    for c in selected:
        lines.append("")
        lines.append(f"### [{c.id or c.path.stem}] {c.title or '(untitled)'}")
        lines.append(
            f"- track: {c.track or '-'} · status: {c.status} · "
            f"value_score: {c.value_score if c.value_score is not None else '-'}"
        )
        if c.source_url:
            lines.append(f"- source: {c.source_url} ({c.source_type or '-'})")
        else:
            lines.append(f"- source: ({c.source_type or '-'})")
        if c.reviewed_at or c.review_after:
            lines.append(
                f"- reviewed_at: {_d(c.reviewed_at)} · review_after: {_d(c.review_after)}"
            )
        lines.append(f"- path: {c.rel_path}")

        body = _safe_body(c.path)
        excerpt = extract_section(body, "Source Excerpt") if body else None
        ai_summary = extract_section(body, "AI Summary") if body else None
        prompts = (
            extract_section(body, "Reusable Prompts / Principles") if body else None
        )

        if excerpt:
            lines.append("\n#### Source Excerpt")
            lines.append(excerpt)
        if ai_summary:
            lines.append("\n#### AI Summary")
            lines.append(ai_summary)
        if options.include_prompts and prompts:
            lines.append("\n#### Reusable Prompts / Principles")
            lines.append(prompts)

    # Action items aggregation
    lines.append("\n## Action Items")
    aggregated: list[str] = []
    for c in selected:
        body = _safe_body(c.path)
        if not body:
            continue
        seg = extract_section(body, "Action Items")
        if seg:
            aggregated.append(f"- from [{c.id or c.path.stem}]:\n{_indent(seg)}")
    if not aggregated:
        lines.append("_(no action items)_")
    else:
        lines.extend(aggregated)

    # Review due summary
    lines.append("\n## Review Due")
    due = _due_now(selected)
    if not due:
        lines.append("_(none due)_")
    else:
        for c in due:
            overdue = _overdue_days(c.review_after)
            lines.append(
                f"- [{c.id or c.path.stem}]"
                + (f" (overdue {overdue} days)" if overdue > 0 else " (due now)")
            )

    # Safe context hint for LLM
    lines.append("\n## Safe Context Hint for LLM Tools\n")
    lines.append("> 把以下原则告诉调用方 LLM（Claude Code / Copilot / 其他）：")
    lines.append(
        "> - 本文件由 mindforge 生成，含人工审核确认过的长期记忆卡片摘要；"
    )
    lines.append(
        "> - 不含未确认的 AI 推测（ai_inference）与个人笔记（human_note）；"
    )
    lines.append("> - 不含 secret / api_key / source 原文 / prompt 全文；")
    lines.append(
        "> - 优先信任 Source Excerpt（原文事实）与 Reusable Prompts（已沉淀的方法）。"
    )

    return "\n".join(lines).rstrip() + "\n"


def render_project_context_json(
    project_name: str,
    cards: list[CardSummary],
    *,
    options: ProjectContextOptions,
) -> str:
    selected = _select(cards, options)
    now_iso = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
    payload = {
        "version": 1,
        "project": project_name,
        "generated_at": now_iso,
        "include_drafts": options.include_drafts,
        "include_prompts": options.include_prompts,
        "count": len(selected),
        "items": [_card_json(c, include_prompts=options.include_prompts) for c in selected],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False)


# ---------------------------------------------------------------------------
# 内部
# ---------------------------------------------------------------------------


def _select(cards: list[CardSummary], options: ProjectContextOptions) -> list[CardSummary]:
    sorted_cards = sorted(cards, key=_sort_key)
    return sorted_cards[: options.limit]


def _sort_key(c: CardSummary) -> tuple[int, datetime, int, str]:
    # review_after 升序（None 排最后）；同时按 value_score 降序；id 字母序
    has_after = 0 if c.review_after is not None else 1
    after = c.review_after or datetime.max.replace(tzinfo=timezone.utc)
    score = -(c.value_score or 0)
    return (has_after, after, score, c.id or c.path.name)


def _safe_body(path: Path) -> str | None:
    try:
        return read_card_body(path)
    except Exception:
        return None


def _d(dt: datetime | None) -> str:
    if dt is None:
        return "-"
    return dt.date().isoformat()


def _overdue_days(review_after: datetime | None) -> int:
    if review_after is None:
        return 0
    now = datetime.now(timezone.utc).astimezone()
    delta = (now - review_after).total_seconds() / 86400.0
    return max(0, int(delta))


def _due_now(cards: list[CardSummary]) -> list[CardSummary]:
    now = datetime.now(timezone.utc).astimezone()
    return [c for c in cards if c.review_after is not None and c.review_after <= now]


def _indent(s: str, prefix: str = "  ") -> str:
    return "\n".join(prefix + line for line in s.splitlines())


def _card_json(c: CardSummary, *, include_prompts: bool) -> dict:
    body = _safe_body(c.path)
    summary_seg = extract_section(body, "AI Summary") if body else None
    excerpt_seg = extract_section(body, "Source Excerpt") if body else None
    prompts_seg = (
        extract_section(body, "Reusable Prompts / Principles") if body else None
    )
    return {
        "id": c.id,
        "title": c.title,
        "path": c.rel_path,
        "status": c.status,
        "track": c.track,
        "projects": list(c.projects),
        "tags": list(c.tags),
        "source_type": c.source_type,
        "source_url": c.source_url,
        "value_score": c.value_score,
        "reviewed_at": c.reviewed_at.isoformat() if c.reviewed_at else None,
        "review_after": c.review_after.isoformat() if c.review_after else None,
        "source_excerpt": excerpt_seg,
        "ai_summary": summary_seg,
        "reusable_prompts": prompts_seg if include_prompts else None,
    }


__all__ = [
    "ProjectContextOptions",
    "render_project_context_markdown",
    "render_project_context_json",
]
